// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: employee.sql

package postgresql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteEmployee = `-- name: DeleteEmployee :execrows
UPDATE
    employees
SET
    deleted_at = $1
WHERE
    id = $2
AND
    deleted_at IS NULL
`

type DeleteEmployeeParams struct {
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	ID        pgtype.Text        `json:"id"`
}

func (q *Queries) DeleteEmployee(ctx context.Context, arg DeleteEmployeeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEmployee, arg.DeletedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findActiveEmployees = `-- name: FindActiveEmployees :many
SELECT
    id,
    name,
    position,
    employee_id,
    author,
    created_at
FROM
    employees
WHERE
    status = 1
AND
    deleted_at IS NULL
ORDER BY
    name ASC
`

type FindActiveEmployeesRow struct {
	ID         string             `json:"id"`
	Name       string             `json:"name"`
	Position   string             `json:"position"`
	EmployeeID pgtype.Text        `json:"employee_id"`
	Author     string             `json:"author"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) FindActiveEmployees(ctx context.Context) ([]FindActiveEmployeesRow, error) {
	rows, err := q.db.Query(ctx, findActiveEmployees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindActiveEmployeesRow{}
	for rows.Next() {
		var i FindActiveEmployeesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Position,
			&i.EmployeeID,
			&i.Author,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllEmployees = `-- name: FindAllEmployees :many
SELECT
    id,
    name,
    position,
    employee_id,
    status,
    author,
    created_at
FROM
    employees
WHERE
    deleted_at IS NULL
ORDER BY
    name ASC
`

type FindAllEmployeesRow struct {
	ID         string             `json:"id"`
	Name       string             `json:"name"`
	Position   string             `json:"position"`
	EmployeeID pgtype.Text        `json:"employee_id"`
	Status     pgtype.Int4        `json:"status"`
	Author     string             `json:"author"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) FindAllEmployees(ctx context.Context) ([]FindAllEmployeesRow, error) {
	rows, err := q.db.Query(ctx, findAllEmployees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindAllEmployeesRow{}
	for rows.Next() {
		var i FindAllEmployeesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Position,
			&i.EmployeeID,
			&i.Status,
			&i.Author,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findEmployeeByID = `-- name: FindEmployeeByID :one
SELECT
    id,
    name,
    position,
    address,
    employee_id,
    birthplace,
    birthdate,
    photo,
    status,
    author,
    created_at,
    updated_at
FROM
    employees
WHERE
    id = $1
AND
    deleted_at IS NULL
`

type FindEmployeeByIDRow struct {
	ID         string             `json:"id"`
	Name       string             `json:"name"`
	Position   string             `json:"position"`
	Address    pgtype.Text        `json:"address"`
	EmployeeID pgtype.Text        `json:"employee_id"`
	Birthplace pgtype.Text        `json:"birthplace"`
	Birthdate  pgtype.Date        `json:"birthdate"`
	Photo      pgtype.Text        `json:"photo"`
	Status     pgtype.Int4        `json:"status"`
	Author     string             `json:"author"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) FindEmployeeByID(ctx context.Context, dollar_1 pgtype.Text) (FindEmployeeByIDRow, error) {
	row := q.db.QueryRow(ctx, findEmployeeByID, dollar_1)
	var i FindEmployeeByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Position,
		&i.Address,
		&i.EmployeeID,
		&i.Birthplace,
		&i.Birthdate,
		&i.Photo,
		&i.Status,
		&i.Author,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findEmployeesByPosition = `-- name: FindEmployeesByPosition :many
SELECT
    id,
    name,
    position,
    employee_id,
    status,
    author,
    created_at
FROM
    employees
WHERE
    position = $1
AND
    deleted_at IS NULL
ORDER BY
    name ASC
`

type FindEmployeesByPositionRow struct {
	ID         string             `json:"id"`
	Name       string             `json:"name"`
	Position   string             `json:"position"`
	EmployeeID pgtype.Text        `json:"employee_id"`
	Status     pgtype.Int4        `json:"status"`
	Author     string             `json:"author"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) FindEmployeesByPosition(ctx context.Context, dollar_1 pgtype.Text) ([]FindEmployeesByPositionRow, error) {
	rows, err := q.db.Query(ctx, findEmployeesByPosition, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindEmployeesByPositionRow{}
	for rows.Next() {
		var i FindEmployeesByPositionRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Position,
			&i.EmployeeID,
			&i.Status,
			&i.Author,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEmployee = `-- name: InsertEmployee :exec
INSERT INTO employees(id, name, position, address, employee_id, birthplace, birthdate, photo, status, author, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertEmployeeParams struct {
	Column1  pgtype.Text        `json:"column_1"`
	Column2  pgtype.Text        `json:"column_2"`
	Column3  pgtype.Text        `json:"column_3"`
	Column4  pgtype.Text        `json:"column_4"`
	Column5  pgtype.Text        `json:"column_5"`
	Column6  pgtype.Text        `json:"column_6"`
	Column7  pgtype.Date        `json:"column_7"`
	Column8  pgtype.Text        `json:"column_8"`
	Column9  pgtype.Int4        `json:"column_9"`
	Column10 pgtype.Text        `json:"column_10"`
	Column11 pgtype.Timestamptz `json:"column_11"`
}

func (q *Queries) InsertEmployee(ctx context.Context, arg InsertEmployeeParams) error {
	_, err := q.db.Exec(ctx, insertEmployee,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.Column10,
		arg.Column11,
	)
	return err
}

const updateEmployee = `-- name: UpdateEmployee :execrows
UPDATE
    employees
SET
    name = $1,
    position = $2,
    address = $3,
    employee_id = $4,
    birthplace = $5,
    birthdate = $6,
    photo = $7,
    status = $8,
    updated_at = $9
WHERE
    id = $10
AND
    deleted_at IS NULL
`

type UpdateEmployeeParams struct {
	Name       pgtype.Text        `json:"name"`
	Position   pgtype.Text        `json:"position"`
	Address    pgtype.Text        `json:"address"`
	EmployeeID pgtype.Text        `json:"employee_id"`
	Birthplace pgtype.Text        `json:"birthplace"`
	Birthdate  pgtype.Date        `json:"birthdate"`
	Photo      pgtype.Text        `json:"photo"`
	Status     pgtype.Int4        `json:"status"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ID         pgtype.Text        `json:"id"`
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEmployee,
		arg.Name,
		arg.Position,
		arg.Address,
		arg.EmployeeID,
		arg.Birthplace,
		arg.Birthdate,
		arg.Photo,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
