// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: market_fee.sql

package postgresql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteMarketFee = `-- name: DeleteMarketFee :execrows
UPDATE
    market_fees
SET
    deleted_at = $1
WHERE
    id = $2
AND
    deleted_at IS NULL
`

type DeleteMarketFeeParams struct {
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	ID        pgtype.Text        `json:"id"`
}

func (q *Queries) DeleteMarketFee(ctx context.Context, arg DeleteMarketFeeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMarketFee, arg.DeletedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findAllMarketFees = `-- name: FindAllMarketFees :many
SELECT
    id,
    market_id,
    permanent_kiosk_revenue,
    non_permanent_kiosk_revenue,
    collection_status,
    semester,
    year,
    author,
    created_at
FROM
    market_fees
WHERE
    deleted_at IS NULL
ORDER BY
    year DESC, semester DESC
`

type FindAllMarketFeesRow struct {
	ID                       string             `json:"id"`
	MarketID                 string             `json:"market_id"`
	PermanentKioskRevenue    interface{}        `json:"permanent_kiosk_revenue"`
	NonPermanentKioskRevenue interface{}        `json:"non_permanent_kiosk_revenue"`
	CollectionStatus         string             `json:"collection_status"`
	Semester                 string             `json:"semester"`
	Year                     int32              `json:"year"`
	Author                   string             `json:"author"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) FindAllMarketFees(ctx context.Context) ([]FindAllMarketFeesRow, error) {
	rows, err := q.db.Query(ctx, findAllMarketFees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindAllMarketFeesRow{}
	for rows.Next() {
		var i FindAllMarketFeesRow
		if err := rows.Scan(
			&i.ID,
			&i.MarketID,
			&i.PermanentKioskRevenue,
			&i.NonPermanentKioskRevenue,
			&i.CollectionStatus,
			&i.Semester,
			&i.Year,
			&i.Author,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findMarketFeeByID = `-- name: FindMarketFeeByID :one
SELECT
    id,
    market_id,
    num_permanent_kiosks,
    num_non_permanent_kiosks,
    permanent_kiosk_revenue,
    non_permanent_kiosk_revenue,
    collection_status,
    description,
    semester,
    year,
    author,
    created_at,
    updated_at
FROM
    market_fees
WHERE
    id = $1
AND
    deleted_at IS NULL
`

type FindMarketFeeByIDRow struct {
	ID                       string             `json:"id"`
	MarketID                 string             `json:"market_id"`
	NumPermanentKiosks       int32              `json:"num_permanent_kiosks"`
	NumNonPermanentKiosks    int32              `json:"num_non_permanent_kiosks"`
	PermanentKioskRevenue    interface{}        `json:"permanent_kiosk_revenue"`
	NonPermanentKioskRevenue interface{}        `json:"non_permanent_kiosk_revenue"`
	CollectionStatus         string             `json:"collection_status"`
	Description              pgtype.Text        `json:"description"`
	Semester                 string             `json:"semester"`
	Year                     int32              `json:"year"`
	Author                   string             `json:"author"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) FindMarketFeeByID(ctx context.Context, dollar_1 pgtype.Text) (FindMarketFeeByIDRow, error) {
	row := q.db.QueryRow(ctx, findMarketFeeByID, dollar_1)
	var i FindMarketFeeByIDRow
	err := row.Scan(
		&i.ID,
		&i.MarketID,
		&i.NumPermanentKiosks,
		&i.NumNonPermanentKiosks,
		&i.PermanentKioskRevenue,
		&i.NonPermanentKioskRevenue,
		&i.CollectionStatus,
		&i.Description,
		&i.Semester,
		&i.Year,
		&i.Author,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findMarketFeesByMarket = `-- name: FindMarketFeesByMarket :many
SELECT
    id,
    market_id,
    permanent_kiosk_revenue,
    non_permanent_kiosk_revenue,
    collection_status,
    semester,
    year,
    author,
    created_at
FROM
    market_fees
WHERE
    market_id = $1
AND
    deleted_at IS NULL
ORDER BY
    year DESC, semester DESC
`

type FindMarketFeesByMarketRow struct {
	ID                       string             `json:"id"`
	MarketID                 string             `json:"market_id"`
	PermanentKioskRevenue    interface{}        `json:"permanent_kiosk_revenue"`
	NonPermanentKioskRevenue interface{}        `json:"non_permanent_kiosk_revenue"`
	CollectionStatus         string             `json:"collection_status"`
	Semester                 string             `json:"semester"`
	Year                     int32              `json:"year"`
	Author                   string             `json:"author"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) FindMarketFeesByMarket(ctx context.Context, dollar_1 pgtype.Text) ([]FindMarketFeesByMarketRow, error) {
	rows, err := q.db.Query(ctx, findMarketFeesByMarket, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindMarketFeesByMarketRow{}
	for rows.Next() {
		var i FindMarketFeesByMarketRow
		if err := rows.Scan(
			&i.ID,
			&i.MarketID,
			&i.PermanentKioskRevenue,
			&i.NonPermanentKioskRevenue,
			&i.CollectionStatus,
			&i.Semester,
			&i.Year,
			&i.Author,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findMarketFeesBySemesterAndYear = `-- name: FindMarketFeesBySemesterAndYear :many
SELECT
    id,
    market_id,
    permanent_kiosk_revenue,
    non_permanent_kiosk_revenue,
    collection_status,
    semester,
    year,
    author,
    created_at
FROM
    market_fees
WHERE
    semester = $1
AND
    year = $2
AND
    deleted_at IS NULL
ORDER BY
    market_id
`

type FindMarketFeesBySemesterAndYearParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Column2 pgtype.Int4 `json:"column_2"`
}

type FindMarketFeesBySemesterAndYearRow struct {
	ID                       string             `json:"id"`
	MarketID                 string             `json:"market_id"`
	PermanentKioskRevenue    interface{}        `json:"permanent_kiosk_revenue"`
	NonPermanentKioskRevenue interface{}        `json:"non_permanent_kiosk_revenue"`
	CollectionStatus         string             `json:"collection_status"`
	Semester                 string             `json:"semester"`
	Year                     int32              `json:"year"`
	Author                   string             `json:"author"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) FindMarketFeesBySemesterAndYear(ctx context.Context, arg FindMarketFeesBySemesterAndYearParams) ([]FindMarketFeesBySemesterAndYearRow, error) {
	rows, err := q.db.Query(ctx, findMarketFeesBySemesterAndYear, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindMarketFeesBySemesterAndYearRow{}
	for rows.Next() {
		var i FindMarketFeesBySemesterAndYearRow
		if err := rows.Scan(
			&i.ID,
			&i.MarketID,
			&i.PermanentKioskRevenue,
			&i.NonPermanentKioskRevenue,
			&i.CollectionStatus,
			&i.Semester,
			&i.Year,
			&i.Author,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findMarketFeesByYear = `-- name: FindMarketFeesByYear :many
SELECT
    id,
    market_id,
    permanent_kiosk_revenue,
    non_permanent_kiosk_revenue,
    collection_status,
    semester,
    year,
    author,
    created_at
FROM
    market_fees
WHERE
    year = $1
AND
    deleted_at IS NULL
ORDER BY
    market_id, semester
`

type FindMarketFeesByYearRow struct {
	ID                       string             `json:"id"`
	MarketID                 string             `json:"market_id"`
	PermanentKioskRevenue    interface{}        `json:"permanent_kiosk_revenue"`
	NonPermanentKioskRevenue interface{}        `json:"non_permanent_kiosk_revenue"`
	CollectionStatus         string             `json:"collection_status"`
	Semester                 string             `json:"semester"`
	Year                     int32              `json:"year"`
	Author                   string             `json:"author"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) FindMarketFeesByYear(ctx context.Context, dollar_1 pgtype.Int4) ([]FindMarketFeesByYearRow, error) {
	rows, err := q.db.Query(ctx, findMarketFeesByYear, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindMarketFeesByYearRow{}
	for rows.Next() {
		var i FindMarketFeesByYearRow
		if err := rows.Scan(
			&i.ID,
			&i.MarketID,
			&i.PermanentKioskRevenue,
			&i.NonPermanentKioskRevenue,
			&i.CollectionStatus,
			&i.Semester,
			&i.Year,
			&i.Author,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMarketFee = `-- name: InsertMarketFee :exec
INSERT INTO market_fees(
    id, 
    market_id, 
    num_permanent_kiosks, 
    num_non_permanent_kiosks, 
    permanent_kiosk_revenue, 
    non_permanent_kiosk_revenue, 
    collection_status, 
    description, 
    semester, 
    year, 
    author, 
    created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type InsertMarketFeeParams struct {
	Column1  pgtype.Text        `json:"column_1"`
	Column2  pgtype.Text        `json:"column_2"`
	Column3  pgtype.Int4        `json:"column_3"`
	Column4  pgtype.Int4        `json:"column_4"`
	Column5  pgtype.Numeric     `json:"column_5"`
	Column6  pgtype.Numeric     `json:"column_6"`
	Column7  pgtype.Text        `json:"column_7"`
	Column8  pgtype.Text        `json:"column_8"`
	Column9  pgtype.Text        `json:"column_9"`
	Column10 pgtype.Int4        `json:"column_10"`
	Column11 pgtype.Text        `json:"column_11"`
	Column12 pgtype.Timestamptz `json:"column_12"`
}

func (q *Queries) InsertMarketFee(ctx context.Context, arg InsertMarketFeeParams) error {
	_, err := q.db.Exec(ctx, insertMarketFee,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.Column10,
		arg.Column11,
		arg.Column12,
	)
	return err
}

const updateMarketFee = `-- name: UpdateMarketFee :execrows
UPDATE
    market_fees
SET
    market_id = $1,
    num_permanent_kiosks = $2,
    num_non_permanent_kiosks = $3,
    permanent_kiosk_revenue = $4,
    non_permanent_kiosk_revenue = $5,
    collection_status = $6,
    description = $7,
    semester = $8,
    year = $9,
    updated_at = $10
WHERE
    id = $11
AND
    deleted_at IS NULL
`

type UpdateMarketFeeParams struct {
	MarketID                 pgtype.Text        `json:"market_id"`
	NumPermanentKiosks       pgtype.Int4        `json:"num_permanent_kiosks"`
	NumNonPermanentKiosks    pgtype.Int4        `json:"num_non_permanent_kiosks"`
	PermanentKioskRevenue    pgtype.Numeric     `json:"permanent_kiosk_revenue"`
	NonPermanentKioskRevenue pgtype.Numeric     `json:"non_permanent_kiosk_revenue"`
	CollectionStatus         pgtype.Text        `json:"collection_status"`
	Description              pgtype.Text        `json:"description"`
	Semester                 pgtype.Text        `json:"semester"`
	Year                     pgtype.Int4        `json:"year"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	ID                       pgtype.Text        `json:"id"`
}

func (q *Queries) UpdateMarketFee(ctx context.Context, arg UpdateMarketFeeParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateMarketFee,
		arg.MarketID,
		arg.NumPermanentKiosks,
		arg.NumNonPermanentKiosks,
		arg.PermanentKioskRevenue,
		arg.NonPermanentKioskRevenue,
		arg.CollectionStatus,
		arg.Description,
		arg.Semester,
		arg.Year,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
