// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgresql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Commodity struct {
	ID              string             `json:"id"`
	Name            string             `json:"name"`
	Price           pgtype.Numeric     `json:"price"`
	Unit            string             `json:"unit"`
	PublishDate     pgtype.Date        `json:"publish_date"`
	Description     pgtype.Text        `json:"description"`
	CommodityTypeID string             `json:"commodity_type_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Author          string             `json:"author"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type CommodityType struct {
	ID          string             `json:"id"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Author      string             `json:"author"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type Employee struct {
	ID         string             `json:"id"`
	Name       string             `json:"name"`
	Position   string             `json:"position"`
	Address    pgtype.Text        `json:"address"`
	EmployeeID pgtype.Text        `json:"employee_id"`
	Birthplace pgtype.Text        `json:"birthplace"`
	Birthdate  pgtype.Date        `json:"birthdate"`
	Photo      pgtype.Text        `json:"photo"`
	Status     pgtype.Int4        `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	Author     string             `json:"author"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type Greeting struct {
	ID        string             `json:"id"`
	Message   string             `json:"message"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Author    string             `json:"author"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Ikm struct {
	ID           string             `json:"id"`
	Description  string             `json:"description"`
	VillageID    string             `json:"village_id"`
	BusinessType string             `json:"business_type"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Author       string             `json:"author"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type IkmType struct {
	ID             string             `json:"id"`
	DocumentName   string             `json:"document_name"`
	FileUrl        string             `json:"file_url"`
	PublicInfoType string             `json:"public_info_type"`
	Description    pgtype.Text        `json:"description"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Author         string             `json:"author"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type LegalDocument struct {
	ID           string             `json:"id"`
	DocumentName string             `json:"document_name"`
	FileUrl      string             `json:"file_url"`
	DocumentType string             `json:"document_type"`
	Description  pgtype.Text        `json:"description"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Author       string             `json:"author"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type LegalDocumentType struct {
	ID          string             `json:"id"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Author      string             `json:"author"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type Market struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Author    string             `json:"author"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type MarketFee struct {
	ID                       string             `json:"id"`
	MarketID                 string             `json:"market_id"`
	NumPermanentKiosks       int32              `json:"num_permanent_kiosks"`
	NumNonPermanentKiosks    int32              `json:"num_non_permanent_kiosks"`
	PermanentKioskRevenue    pgtype.Numeric     `json:"permanent_kiosk_revenue"`
	NonPermanentKioskRevenue pgtype.Numeric     `json:"non_permanent_kiosk_revenue"`
	CollectionStatus         string             `json:"collection_status"`
	Description              pgtype.Text        `json:"description"`
	Semester                 string             `json:"semester"`
	Year                     int32              `json:"year"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	Author                   string             `json:"author"`
	DeletedAt                pgtype.Timestamptz `json:"deleted_at"`
}

type News struct {
	ID        string             `json:"id"`
	Title     string             `json:"title"`
	Content   string             `json:"content"`
	Author    string             `json:"author"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Photo struct {
	ID          string             `json:"id"`
	CategoryID  string             `json:"category_id"`
	Title       string             `json:"title"`
	FileUrl     pgtype.Text        `json:"file_url"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Author      string             `json:"author"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type PhotoCategory struct {
	ID        string             `json:"id"`
	Category  string             `json:"category"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Author    string             `json:"author"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type PublicInformation struct {
	ID             string             `json:"id"`
	DocumentName   string             `json:"document_name"`
	FileUrl        string             `json:"file_url"`
	PublicInfoType string             `json:"public_info_type"`
	Description    pgtype.Text        `json:"description"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Author         string             `json:"author"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type PublicInformationType struct {
	ID          string             `json:"id"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Author      string             `json:"author"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type Role struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Sector struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Author      string             `json:"author"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type Subdistrict struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Author    string             `json:"author"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID        string             `json:"id"`
	RoleID    string             `json:"role_id"`
	Username  string             `json:"username"`
	Password  string             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Video struct {
	ID          string             `json:"id"`
	Title       string             `json:"title"`
	Link        string             `json:"link"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Author      string             `json:"author"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type Village struct {
	ID            string             `json:"id"`
	SubdistrictID string             `json:"subdistrict_id"`
	Name          string             `json:"name"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Author        string             `json:"author"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type VisionMission struct {
	ID        string             `json:"id"`
	Vision    string             `json:"vision"`
	Mission   string             `json:"mission"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Author    string             `json:"author"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}
