// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: public_information_type.sql

package postgresql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePublicInfoType = `-- name: DeletePublicInfoType :execrows
UPDATE
    public_information_types
SET
    deleted_at = $1
WHERE
    id = $2
AND
    deleted_at IS NULL
`

type DeletePublicInfoTypeParams struct {
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	ID        string             `json:"id"`
}

func (q *Queries) DeletePublicInfoType(ctx context.Context, arg DeletePublicInfoTypeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePublicInfoType, arg.DeletedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findAllPublicInfoTypes = `-- name: FindAllPublicInfoTypes :many
SELECT
    id,
    description,
    author,
    created_at
FROM
    public_information_types
WHERE
    deleted_at IS NULL
ORDER BY
    description ASC
`

type FindAllPublicInfoTypesRow struct {
	ID          string             `json:"id"`
	Description string             `json:"description"`
	Author      string             `json:"author"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) FindAllPublicInfoTypes(ctx context.Context) ([]FindAllPublicInfoTypesRow, error) {
	rows, err := q.db.Query(ctx, findAllPublicInfoTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindAllPublicInfoTypesRow{}
	for rows.Next() {
		var i FindAllPublicInfoTypesRow
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Author,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPublicInfoTypeByID = `-- name: FindPublicInfoTypeByID :one
SELECT
    id,
    description,
    author,
    created_at,
    updated_at
FROM
    public_information_types
WHERE
    id = $1
AND
    deleted_at IS NULL
`

type FindPublicInfoTypeByIDRow struct {
	ID          string             `json:"id"`
	Description string             `json:"description"`
	Author      string             `json:"author"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) FindPublicInfoTypeByID(ctx context.Context, id string) (FindPublicInfoTypeByIDRow, error) {
	row := q.db.QueryRow(ctx, findPublicInfoTypeByID, id)
	var i FindPublicInfoTypeByIDRow
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Author,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPublicInfoType = `-- name: InsertPublicInfoType :exec
INSERT INTO public_information_types(id, description, author, created_at)
VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type InsertPublicInfoTypeParams struct {
	ID          string             `json:"id"`
	Description string             `json:"description"`
	Author      string             `json:"author"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertPublicInfoType(ctx context.Context, arg InsertPublicInfoTypeParams) error {
	_, err := q.db.Exec(ctx, insertPublicInfoType,
		arg.ID,
		arg.Description,
		arg.Author,
		arg.CreatedAt,
	)
	return err
}

const updatePublicInfoType = `-- name: UpdatePublicInfoType :execrows
UPDATE
    public_information_types
SET
    description = $1,
    updated_at = $2
WHERE
    id = $3
AND
    deleted_at IS NULL
`

type UpdatePublicInfoTypeParams struct {
	Description string             `json:"description"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ID          string             `json:"id"`
}

func (q *Queries) UpdatePublicInfoType(ctx context.Context, arg UpdatePublicInfoTypeParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePublicInfoType, arg.Description, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
