[app]
port=
corsorigin=["*"]

[database]
name=""
username=""
password=""
port=
address=""
driver=""
maxconns=
minconns=
maxconnlifetime=
maxconnidletime=
healthcheckperiod=
conntimeout=

[jwt]
secret=""
issuer=""
subject=""