services:
  postgres:
    container_name: disperdagin-postgres
    image: postgres:16-alpine3.20
    volumes:
      - postgres_data_disperdagin:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db_disperdagin
      POSTGRES_USER: devs
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  api:
    container_name: disperdagin-api
    build:
      context: ..
      dockerfile: docker/dev.dockerfile
    working_dir: /backend-alter-io
    ports:
      - 4000:4000
    volumes:
      - ../server:/backend-alter-io
    environment:
      APP_ENV: DEVELOPMENT
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
